### ISSUE TITLE
didn't work for sprayCloud

### ISSUE THREAD

**Issue by FR13ndSDP** [blueCFD/lagrangianExtraFunctionObjects#2] opened 2020-03-21 11:12 UTC
Hi, wyldckat

Thanks for your great work. I have  OpenFOAM 7.0 running on WSL ubuntu, and use Paraview.exe to do post processing.  It worked fine to me when I run tutorial case *MPPICFoam_column*, it worked and generated positions.orig. But when i try to do the same thing in tutorial case /sprayFoam/aachenBomb, it did not generate .orig file. It confused me. Here is the code block I added to the controlDict:

```
functions
{
	#includeFunc Qdot          //it's in the original controlDict
    writeCloudOldStyle1
    {
        type        writeCloudOldStyle;
        libs        ("liblagrangianExtraFunctionObjects.so");

        writeControl writeTime;

        clouds
        (
            sprayCloud
        );
    }
}
```

**Comment by wyldckat** [comment] 2020-04-01 15:31
@FR13ndSDP: I've merged @ZhangYanTJU's pull request #3 a few minutes ago and it should now support this capability which you have asked for!

Please let us know if it works as intended!

**Comment by FR13ndSDP** [comment] 2020-04-06 14:29
@wyldckat :Thank you all, It works! There is a little trap though, I noticed that if `writeFormat` in controlDict is set to `binary`, then the `position.orig` won't be generated, but after I set it to `ascii`, it is fine

**Comment by FR13ndSDP** [comment] 2020-04-06 14:38
@wyldckat : Thank you all, it works! 👍 
There is one thing I noticed that if `writeFormat` in controlDict is set to `binary`, then `reconstructPar` and post processing would have problem because the `positions` file is in ascii. Is there a way to change write format of `positions` ?

**Comment by FR13ndSDP** [comment] 2020-04-06 14:44
@FR13ndSDP  By the way,  header of position.orig is wrong when writeFormat is set to binary

**Closed as completed** 2022-03-13 09:16 UTC
